---
title: "Final Project"
author: "Aasha Reddy"
date: "3/16/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load libraries
library(lubridate)
library(ggplot2)
library(forecast)  
library(Kendall)
library(tseries)
library(outliers)
library(tidyverse)
library(smooth)
library(sarima)
```

India 20 year temp data - This is the data I will use
From this kaggle: https://www.kaggle.com/jonathanbouchet/new-delhi-20-years-of-weather-data/data?select=testset.csv

```{r}
# load data
india_20 <- read.csv("Final Project/data/india_20.csv")

# clean data with dates, group by hour
x <- india_20 %>%
  mutate(datetime_utc = gsub("-.*", "", datetime_utc), 
         date = ymd(datetime_utc), 
         X_hum = as.numeric(X_hum)) %>%
  group_by(date) %>%
  summarize(temp = mean(X_tempm, na.rm = TRUE), 
            humidity = mean(X_hum, na.rm = TRUE), 
            dew_pt_temp = mean(X_dewptm, na.rm = TRUE), 
            visibility = mean(X_vism, na.rm = TRUE))

# get rid of visibility outlier by swapping it with day before
max_vis <- which.max(x$visibility)
x$visibility[max_vis] <- x$visibility[max_vis - 1]

ggplot(x, aes(x = date, y = temp)) + 
  geom_line() + 
  labs(title = "Average Daily Temperature (1996 - 2017)", 
       y = "Temperature (Celcius)", 
       x = "Year") + 
  theme_bw()

ggplot(x, aes(x = date, y = humidity)) + 
  geom_line() + 
  labs(title = "Average Daily Humidity (1996 - 2017)", 
       y = "Humidity", 
       x = "Year") + 
  theme_bw()

ggplot(x, aes(x = date, y = dew_pt_temp)) + 
  geom_line() + 
  labs(title = "Average Daily Dew Point Temp. (1996 - 2017)", 
       y = "Dew Point Temperature (Degrees Celcius)", 
       x = "Year") + 
  theme_bw()

ggplot(x, aes(x = date, y = visibility)) + 
  geom_line() + 
  labs(title = "Average Daily Visibility (1996 - 2017)", 
       y = "Visibility", 
       x = "Year") + 
  theme_bw()

# aggregate plots daily
x %>%
  pivot_longer(cols = 2:5) %>%
  mutate(name = case_when(
    name == "temp" ~ "Temperature (Degrees Celcius)", 
    name == "humidity" ~ "Humidity (%)", 
    name == "visibility" ~ "Visibility (km)", 
    name == "dew_pt_temp" ~ "Dew Point Temperature (Degrees Celcius)"
  )) %>%
  ggplot(., aes(x = date, y = value)) + 
  geom_line() + 
  facet_wrap(~name, scales = "free") + 
  theme_bw() + 
  labs(title = "Daily Average Weather in New Delhi (1996 - 2017)", 
       x = "Year", 
       y = "")
```

```{r}
# Aggregate plots monthly 

# clean data with dates, group by hour
x <- india_20 %>%
  mutate(date = gsub("-.*", "", datetime_utc), 
         X_hum = as.numeric(X_hum)) %>%
  group_by(date) %>%
  summarize(temp = mean(X_tempm, na.rm = TRUE), 
            humidity = mean(X_hum, na.rm = TRUE), 
            dew_pt_temp = mean(X_dewptm, na.rm = TRUE), 
            visibility = mean(X_vism, na.rm = TRUE))

x <- india_20 %>%
  mutate(datetime_utc = substr(datetime_utc,1,6), 
         date = ym(datetime_utc), 
         X_hum = as.numeric(X_hum))  %>%
  group_by(date) %>%
  summarize(temp = mean(X_tempm, na.rm = TRUE), 
            humidity = mean(X_hum, na.rm = TRUE), 
            dew_pt_temp = mean(X_dewptm, na.rm = TRUE), 
            visibility = mean(X_vism, na.rm = TRUE))

# get rid of visibility outlier by swapping it with day before
max_vis <- which.max(x$visibility)
x$visibility[max_vis] <- x$visibility[max_vis - 1]

# aggregate plots daily
x %>%
  pivot_longer(cols = 2:5) %>%
  mutate(name = case_when(
    name == "temp" ~ "Temperature (Degrees Celcius)", 
    name == "humidity" ~ "Humidity (%)", 
    name == "visibility" ~ "Visibility (km)", 
    name == "dew_pt_temp" ~ "Dew Point Temperature (Degrees Celcius)"
  )) %>%
  ggplot(., aes(x = date, y = value)) + 
  geom_line() + 
  facet_wrap(~name, scales = "free") + 
  theme_bw() + 
  labs(title = "Monthly Average Weather in New Delhi (1996 - 2017)", 
       x = "Year", 
       y = "")
```


# Introduction 


# Data 

The dataset captures daily weather in New Delhi, India from 1/1/2013 to 4/27/2017 for mean daily temperature, wind speed, humidity and mean air pressure. This data comes from kaggle: https://www.kaggle.com/jonathanbouchet/new-delhi-20-years-of-weather-data/data?select=testset.csv. 

# Methods


# Results 


# Discussion